Repository kubernetes-sigs/kube-storage-version-migrator, pull requests merged in 2019-11, with the labels that each got.

#39 recreate StorageVersionMigration as cluster scoped
  pkg/initializer/initializer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#43 migrator: add common network errors as retriable errors
  pkg/migrator/errors.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#40 move from glog to klog
  cmd/initializer/initializer.go
  cmd/migrator/migrator.go
  cmd/trigger/trigger.go
  pkg/controller/kubemigrator.go
  pkg/initializer/discover.go
  pkg/trigger/discovery_handler.go
  pkg/trigger/migration_handler.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#42 fix golint error
  pkg/migrator/core_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#44 Throttle core migrator List request
  pkg/migrator/core.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#45 Fix flaky test
  pkg/controller/indexer_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#48 Add version to user agent
  Makefile
  cmd/initializer/app/initializer.go
  cmd/migrator/app/migrator.go
  cmd/trigger/app/trigger.go
  pkg/version/version.go
  test/e2e/tests/chaos.go
  test/e2e/tests/crd-migration.go
Labels: approved, cncf-cla: yes, lgtm, size/M
